name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npx eslint . --max-warnings 200

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test
    environment: flight booking
    strategy:
      matrix:
        platform: [android, ios]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build App
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            eas build --platform ${{ matrix.platform }} --profile preview --non-interactive
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            eas build --platform ${{ matrix.platform }} --profile staging --non-interactive
            eas build --platform ${{ matrix.platform }} --profile testing --non-interactive
          fi

      - name: Download Latest Artifact
        run: |
          eas build:list --limit 1 --json | jq -r '.[0].artifacts.buildUrl' | xargs curl -L -o app-${{ matrix.platform }}.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.platform }}
          path: app-${{ matrix.platform }}.tar.gz

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            🚀 New Testing Release for commit ${{ github.sha }}

            ## Builds Included:
            ✅ Android APK  
            ✅ iOS IPA  

            Download from **release assets** or from **Actions Artifacts**.
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
